%YAML:1.0
# data
# the tum dataset directory, change it to yours! 
# dataset_dir: /media/xiang/Data/Dataset/Kitti/dataset/sequences/00
# dataset_dir: /media/cw/SD_PSSD/moying_transfer_area_7.19/slam_learning/ch13_dataset/data_odometry_gray/dataset/sequences/05
dataset_dir: /home/cw/code/slam_learning/data_odometry_gray_ch13/00

# camera intrinsics
camera.fx: 517.3
camera.fy: 516.5
camera.cx: 325.1
camera.cy: 249.7

num_features: 150
num_features_init: 50
num_features_tracking: 50
